
title: imgBB bulk downloader
description: >- 
 imgBB bulk downloader - bulk download images from imgbb. Paste links and click download.
baseurl: "" 
url: "https://deontic.github.io/imgBB-web-bulk-downloader" 
github_username:  deontic

theme: minima
plugins:
  - jekyll-seo-tag


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
