
title: imgBB bulk image downloader
description: >- 
 imgBB bulk downloader - a tool to easily download images from imgbb.com in bulk. Simply paste your links and click the download button to mass download images.
baseurl: "" 
url: "https://deontic.github.io/imgBB-web-bulk-downloader/" 
github_username:  deontic

theme: minima
plugins:
  - jekyll-seo-tag


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
